MyPass/Controllers/EntriesController.cs
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyPass.Core;
using MyPass.Core.Models;
using MyPass.Core.ViewModels;

namespace MyPass.Controllers
{
    public class EntriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EntriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize]
        public ActionResult Create()
        {

            var viewModel =  new EntryFormViewModel();

            viewModel.Categories = _unitOfWork.CategoryRepository.GetCategories();
            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(EntryFormViewModel viewModel)
        {

            //if (!ModelState.IsValid)
            //{
            //    viewModel.Categories = _unitOfWork.CategoryRepository.GetCategories();
            //    return View("GigForm", viewModel);
            //}

            var entry = new Entry
            {
                CreatedById = new Guid(User.Identity.GetUserId()),
                CreatedOn = viewModel.GetDateTime(),
                CategoryId = viewModel.CategoryId,
                Name = viewModel.Name,
                Description =  viewModel.Desription
            };

            _unitOfWork.EntryRepository.Add(entry);
            _unitOfWork.SaveChanges();

            return RedirectToAction("Index", "Home");

        }
    }
}

MyPass/Views/Entries/Create.cshtml
@model MyPass.Core.ViewModels.EntryFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Entry</h2>
@using (Html.BeginForm("Create", "Entries"))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>    
    <div class="form-group">
        @Html.LabelFor(x => x.Desription)
        @Html.TextAreaFor(x => x.Desription, new { @class = "form-control", rows=3 })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Date)
        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Time)
        @Html.TextBoxFor(x => x.Time, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.CategoryId)
        @Html.DropDownListFor(x => x.CategoryId, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">
        Save
    </button>
}